import streamlit as st
import pandas as pd
import requests
import time

# APP CONFIGURATION
st.set_page_config(page_title="Tinay's Price Calculator", page_icon="🧮", layout="centered")
st.title("🧮 Tinay's Personal Retail Price Calculator")
st.markdown("Calculate wholesale item prices and manage your master store retail price book.")

tab1, tab2 = st.tabs(["📝 Price Calculator", "📊 Price Master List"])

# --- CORE DATA LOADER BYPASS ENGINE ---
sheet_id = "14XUh3otWt1EoVM3RuLPceHhAaKF5iigOQO44mMcN2Fo"
# Direct public sheet layout query path forcing explicit target on Sheet1
csv_url = f"https://google.com{sheet_id}/gviz/tq?tqx=out:csv&sheet=Sheet1&t={int(time.time())}"

try:
    # Direct read-in bypasses intermediate web scraping requests
    df_master = pd.read_csv(csv_url)
    df_master.columns = df_master.columns.str.strip()
    
    # Cleans up any unnamed artifact columns generated by Google Sheets layout spacing
    df_master = df_master.loc[:, ~df_master.columns.str.contains('^Unnamed')]
except Exception as e:
    # Fail-safe structural schema configuration
    df_master = pd.DataFrame(columns=["Product Name", "Capital Cost", "Markup", "Profit", "Selling Price"])

# Verify structural column compliance
required_columns = ["Product Name", "Capital Cost", "Markup", "Profit", "Selling Price"]
for col in required_columns:
    if col not in df_master.columns:
        df_master[col] = None

# Reorder layout and strip empty text records cleanly
df_master = df_master[required_columns]

# =========================================================
# TAB 1: SMART PRICE CALCULATOR
with tab1:
    st.subheader("Compute Product Pricing")
    
    with st.form("calculator_form", clear_on_submit=False):
        prod_name = st.text_input("Product Name", placeholder="e.g., Shampoo, Noodles, Soap")
        
        col1, col2 = st.columns(2)
        with col1:
            capital = st.number_input("Capital Cost (₱)", min_value=0.0, step=1.0, value=0.0)
        with col2:
            markup = st.number_input("Desired Markup (%)", min_value=0.0, step=1.0, value=10.0)
            
        profit = capital * (markup / 100.0)
        retail_price = capital + profit
        
        st.markdown("---")
        res_col1, res_col2 = st.columns(2)
        with res_col1:
            st.metric(label="Profit per Unit", value=f"₱{profit:,.2f}")
        with res_col2:
            st.metric(label="Final Retail Selling Price", value=f"₱{retail_price:,.2f}")
        
        st.markdown("---")
        
        authorize_save = st.checkbox("Confirm: I am ready to push this calculation to the Cloud Sheet registry")
        
        submit_btn = st.form_submit_button("📥 Save to Master Price List", use_container_width=True)
        
        if submit_btn:
            if not prod_name.strip():
                st.warning("Please type a valid Product Name before saving.")
            elif not authorize_save:
                st.error("⚠️ Data blocked! You must check the confirmation box above before clicking save.")
            else:
                payload = {
                    "product": prod_name,
                    "capital": capital,
                    "markup": f"{markup}%",
                    "profit": round(profit, 2),
                    "selling": round(retail_price, 2)
                }
                
                WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbzO0lSxhF4KBZPtyOpXEQgb18Ha74KLKMMnekvpndxsogEnjmDHZalITOk0WYVpJdaowg/exec"
                
                with st.spinner("Uploading row entry directly to your cloud data books..."):
                    try:
                        response = requests.post(WEBHOOK_URL, json=payload)
                        if response.status_code == 200:
                            st.toast(f"✅ Successfully saved '{prod_name}' to your Master Sheet!")
                            time.sleep(1.0)
                            st.rerun()
                        else:
                            st.error(f"Failed to connect to pipeline. Server status: {response.status_code}")
                    except Exception as e:
                        st.error("Connection error. Make sure your Apps Script Webhook is active.")

# =========================================================
# TAB 2: PRICE MASTER LIST
with tab2:
    st.subheader("Your Cloud Price Master List")
    
    # Drops any completely empty or blank row headers from showing up in your list
    df_clean = df_master.dropna(subset=["Product Name"])
    df_clean = df_clean[df_clean["Product Name"].str.strip() != ""]
    
    if df_clean.empty:
        st.info("Your Google Sheet is connected, but no valid products were detected. Use Tab 1 to insert an entry!")
    else:
        # Renders the live rows on screen
        st.dataframe(df_clean, use_container_width=True, hide_index=True)
