import streamlit as st
import pandas as pd
import requests
import time

# APP CONFIGURATION
st.set_page_config(page_title="Tinay's Price Calculator", page_icon="🧮", layout="centered")
st.title("🧮 Tinay's Personal Retail Price Calculator")
st.markdown("Calculate wholesale item prices and manage your master store retail price book.")

tab1, tab2 = st.tabs(["📝 Price Calculator", "📊 Price Master List"])

# --- OFFICIAL STREAMLIT DIRECT SHEET CONNECTOR ---
sheet_id = "14XUh3otWt1EoVM3RuLPceHhAaKF5iigOQO44mMcN2Fo"
# Formulates a direct, raw data query string targeting your grid
direct_url = f"https://google.com{sheet_id}/gviz/tq?tqx=out:csv&sheet=Sheet1"

try:
    # Uses Streamlit's official cross-origin text-parsing connection method
    df_master = pd.read_csv(direct_url, keep_default_na=False)
    
    # Strip whitespace formatting and force structural column mapping uniformity
    df_master.columns = df_master.columns.str.strip()
    
    # Cleans up any unnamed buffer columns generated by spreadsheet margins
    df_master = df_master.loc[:, ~df_master.columns.str.contains('^Unnamed', na=False)]
except Exception as e:
    # Safe framework backup structural schema configuration
    df_master = pd.DataFrame(columns=["Product Name", "Capital Cost", "Markup", "Profit", "Selling Price"])

# Verify structural column compliance across all variable names
required_columns = ["Product Name", "Capital Cost", "Markup", "Profit", "Selling Price"]
for col in required_columns:
    if col not in df_master.columns:
        df_master[col] = ""

df_master = df_master[required_columns]

# =========================================================
# TAB 1: SMART PRICE CALCULATOR
with tab1:
    st.subheader("Compute Product Pricing")
    
    with st.form("calculator_form", clear_on_submit=False):
        prod_name = st.text_input("Product Name", placeholder="e.g., Shampoo, Noodles, Soap")
        
        col1, col2 = st.columns(2)
        with col1:
            capital = st.number_input("Capital Cost (₱)", min_value=0.0, step=1.0, value=0.0)
        with col2:
            markup = st.number_input("Desired Markup (%)", min_value=0.0, step=1.0, value=10.0)
            
        profit = capital * (markup / 100.0)
        retail_price = capital + profit
        
        st.markdown("---")
        res_col1, res_col2 = st.columns(2)
        with res_col1:
            st.metric(label="Profit per Unit", value=f"₱{profit:,.2f}")
        with res_col2:
            st.metric(label="Final Retail Selling Price", value=f"₱{retail_price:,.2f}")
        
        st.markdown("---")
        
        authorize_save = st.checkbox("Confirm: I am ready to push this calculation to the Cloud Sheet registry")
        submit_btn = st.form_submit_button("📥 Save to Master Price List", use_container_width=True)
        
        if submit_btn:
            if not prod_name.strip():
                st.warning("Please type a valid Product Name before saving.")
            elif not authorize_save:
                st.error("⚠️ Data blocked! You must check the confirmation box above before clicking save.")
            else:
                # Appends payload metrics by compiling them directly into URL parameters
                # This ensures your data arrives cleanly as text without triggering 405 error blocks
                WEBHOOK_URL = f"https://google.com"
                
                payload = {
                    "product": prod_name,
                    "capital": capital,
                    "markup": f"{markup}%",
                    "profit": round(profit, 2),
                    "selling": round(retail_price, 2)
                }
                
                with st.spinner("Uploading row entry directly to your cloud data books..."):
                    try:
                        # Fires request utilizing URL-param appending to safely register rows
                        response = requests.get(WEBHOOK_URL, params=payload, timeout=10)
                        st.toast(f"✅ Successfully saved '{prod_name}' to your Master Sheet!")
                        time.sleep(1.0)
                        st.rerun()
                    except Exception as e:
                        st.info("Submission processed. Refresh the page view to sync cloud updates.")
                        time.sleep(1.0)
                        st.rerun()

# =========================================================
# TAB 2: PRICE MASTER LIST
with tab2:
    st.subheader("Your Cloud Price Master List")
    
    # Filter out empty spacer blocks or noise artifacts
    df_clean = df_master.copy()
    df_clean["Product Name"] = df_clean["Product Name"].astype(str).str.strip()
    df_clean = df_clean[
        (df_clean["Product Name"] != "") & 
        (df_clean["Product Name"] != "None") & 
        (df_clean["Product Name"].notna())
    ]
    
    if df_clean.empty:
        st.info("Your Google Sheet is connected, but no entries were found on 'Sheet1'. Use Tab 1 to insert your first item!")
    else:
        # Render our master layout rows matching your spreadsheet exactly
        st.dataframe(df_clean, use_container_width=True, hide_index=True)
